import {categories,issues,byId,common,search,discord,safety} from './content.mjs';
const v=Number(document.body.dataset.variant),app=document.querySelector('#app'),states=new Map();
const names=['','Quick find','Help workspace','Find my next step','Follow the action','Open guidebook'];
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cat=id=>categories.find(c=>c.id===id);
const link=(i,detail=false)=>`<a class="issue-row" href="#problem/${i.id}"><span><strong>${e(i.title)}</strong>${detail?`<small>${e(i.problem)}</small>`:''}</span><span aria-hidden="true">↗</span></a>`;
const categoryLink=c=>`<a class="topic" href="#category/${c.id}"><span class="topic-symbol" aria-hidden="true">${{connect:'⌁',nightmare:'◇',craft:'⬡',purchases:'□',account:'◎',progress:'↗'}[c.id]}</span><span><strong>${e(c.title)}</strong><small>${e(c.description)}</small></span><span aria-hidden="true">›</span></a>`;
function searchBox(){return `<div class="search"><label for="help-search">Search a problem or error code</label><div class="search-field"><span aria-hidden="true">⌕</span><input id="help-search" type="search" role="combobox" aria-autocomplete="list" aria-controls="search-results" aria-expanded="false" autocomplete="off" placeholder="Try CODE(0), missing purchase, Dust…" maxlength="120"><button data-clear aria-label="Clear search">×</button></div><div class="search-examples"><span>Try</span><button data-query="CODE(0)">CODE(0)</button><button data-query="purchase missing">missing purchase</button><button data-query="Glider pending">Glider pending</button></div><div id="search-results" role="listbox" aria-label="Matching problems" hidden></div><span id="search-status" class="sr-only" aria-live="polite"></span></div>`;}
function intro(title,sub){return `<div class="intro"><span class="eyebrow">Clash of Coins / Help</span><h1>${title}</h1><p>${sub}</p></div>`;}
function home(){document.title=`${names[v]} · CoC Help`;let body='';
 if(v===1)body=`${intro('What needs fixing?','Find your symptom. Try a safe check. Get back to your game.')}${searchBox()}<section><div class="section-head"><h2>Common problems</h2><a href="#browse">All topics →</a></div><div class="common-grid">${common.map(id=>link(byId[id])).join('')}</div></section><section><h2>Browse by topic</h2><div class="topics">${categories.map(categoryLink).join('')}</div></section>`;
 if(v===2)body=`${intro('Your help workspace','Pick a topic to keep its problems and fixes side by side.')}${searchBox()}<div class="workspace"><aside class="topic-rail"><h2>Topics</h2>${categories.map(categoryLink).join('')}</aside><section class="workspace-start"><span class="eyebrow">Start with a symptom</span><h2>What do you see?</h2><p>Select a problem to open its safe checks in this workspace.</p>${common.map(id=>link(byId[id])).join('')}</section></div>`;
 if(v===3)body=`<div class="triage-home">${intro('Let’s find the next step','Start with what happened. You will not need to sign in here.')}<div class="triage-panel"><span class="eyebrow">Choose the closest match</span><div class="triage-choices">${[['connect','The game will not work','Loading, room entry or a disconnect'],['purchases','Something is missing','A paid item or completed reward'],['craft','An action did not finish','Craft, claim, upgrade or dismantle'],['account','My account or wallet is wrong','Sign-in, linked wallets or safety'],['nightmare','My session or points look wrong','Nightmare, Keys or AP'],['progress','My progress is not updating','Rank, referrals or Glider']].map(([id,t,d])=>`<a href="#category/${id}" class="triage-choice"><span><strong>${t}</strong><small>${d}</small></span><span aria-hidden="true">→</span></a>`).join('')}</div></div><div class="search-alternative"><h2>Already know the error?</h2>${searchBox()}</div></div>`;
 if(v===4)body=`${intro('Where did things stop?','Follow the action you were taking, then choose the result you saw.')}${searchBox()}<div class="journeys">${categories.map((c,n)=>`<section class="journey"><div class="journey-head"><span class="journey-number">${String(n+1).padStart(2,'0')}</span><h2>${e(c.journey)}</h2></div>${issues.filter(i=>i.category===c.id).slice(0,3).map(i=>link(i)).join('')}<a class="all-in-stage" href="#category/${c.id}">All ${e(c.title.toLowerCase())} problems →</a></section>`).join('')}</div>`;
 if(v===5)body=`${intro('One problem. One open guide.','Browse the guidebook without leaving the page. Open a topic to begin.')}${searchBox()}<div class="guidebook">${categories.map(c=>`<details class="topic-book"><summary><span><strong>${e(c.title)}</strong><small>${e(c.description)}</small></span><span class="count">${issues.filter(i=>i.category===c.id).length}</span></summary><div class="book-index">${issues.filter(i=>i.category===c.id).map(i=>link(i,true)).join('')}</div></details>`).join('')}</div>`;
 app.innerHTML=`<div class="container home v${v}-home">${body}<p class="quiet-safety">${e(safety)}</p></div>`;bindSearch();}
function browse(id){const c=cat(id);if(!c){app.innerHTML=`<div class="container">${intro('Browse problems','Choose a topic, then the symptom that matches.')}${searchBox()}<div class="topics">${categories.map(categoryLink).join('')}</div></div>`;bindSearch();return;}
 app.innerHTML=`<div class="container"><a class="back" href="#home">← All topics</a>${intro(v===3?'Which symptom matches?':e(c.title),e(c.description))}${searchBox()}<div class="category-list">${issues.filter(i=>i.category===id).map(i=>link(i,true)).join('')}</div></div>`;bindSearch();}
function state(id){if(!states.has(id))states.set(id,{at:0,history:[],status:'active',message:''});return states.get(id);}
function related(i){return `<section class="related" id="related"><h2>Related problems</h2><p>A different symptom needs a different check.</p>${i.related.slice(0,3).map(id=>link(byId[id])).join('')}</section>`;}
function governance(i){let overdue=new Date()>new Date(i.governance.expires+'T23:59:59Z');return `<details class="governance"><summary>About this guidance${overdue?' · review due':''}</summary><p>${e(i.governance.platform)}</p><dl><dt>Evidence basis</dt><dd>${e(i.governance.source)}</dd><dt>Responsible role</dt><dd>${e(i.governance.owner)} (approval pending)</dd><dt>Editorial check</dt><dd>${i.governance.editorialChecked}; not a product-rule approval</dd><dt>Review / expiry</dt><dd>${i.governance.expires}${overdue?' — overdue; treat guidance as conservative checks only':''}</dd><dt>Publication</dt><dd>Preview guidance. No current policy values or live incidents are claimed.</dd></dl></details>`;}
function fallback(i,s){return `<section class="support" id="support" tabindex="-1"><span class="eyebrow">Last step</span><h2>Still not fixed?</h2><p>${e(s.message||'These safe checks are exhausted. If related problems do not match, a private account or session review is the next step.')}</p><p class="intake"><strong>Have ready:</strong> ${i.details.map(e).join(' · ')}. A screenshot is optional.</p><a class="button primary" href="${discord}" target="_blank" rel="noopener noreferrer">Open Discord support ↗</a><p class="small">Already have a ticket for this issue? Add these details there. This page has not sent a support request.</p><p class="small">${e(safety)}</p></section>`;}
function current(i,s){const f=i.steps[s.at];return `<section class="current-step" id="current-step" tabindex="-1"><div class="step-top"><span class="step-marker">${s.at+1}</span><span class="eyebrow">Possible fixes · ${s.at+1} of ${i.steps.length}</span></div><h2>${e(f.title)}</h2><p>${e(f.action)}</p><p class="expected"><strong>Check the result</strong>${e(f.expected)}</p><h3>What do you see after this check?</h3><div class="answers">${f.answers.map((a,n)=>`<button data-answer="${n}" class="answer"><span>${e(a.label)}</span><span aria-hidden="true">→</span></button>`).join('')}</div><div class="skip"><button data-skip="Already tried — still unresolved">Already tried this</button><button data-skip="Cannot check">I can’t check</button></div></section>`;}
function history(i,s){return s.history.map((a,n)=>`<div class="completed"><span aria-hidden="true">✓</span><span>${e(i.steps[n].title)}<small>${e(a)}</small></span><button data-edit="${n}">Change</button></div>`).join('');}
function result(i,s){return `<section class="outcome ${s.status}" id="outcome" tabindex="-1" role="status"><span class="eyebrow">${s.status==='wait'?'Safe stopping point':'Observed result'}</span><h2>${s.status==='wait'?'Pause here safely':'Your check is complete'}</h2><p>${e(s.message)}</p><a class="button" href="#home">Back to problems</a>${s.status==='wait'?'<button data-unresolved class="button">Still unresolved / cannot follow this</button>':''}<div class="feedback"><span>Was this guidance useful?</span><button data-feedback="yes">Yes</button><button data-feedback="no">No</button><span class="feedback-status" aria-live="polite"></span></div></section>`;}
function article(id,focus=false){const i=byId[id];if(!i){app.innerHTML=`<div class="container">${intro('That guide is unavailable','The link may be old or the guidance is not verified.')}${searchBox()}<a class="button" href="#browse">Browse current problems</a></div>`;bindSearch();return;}
 const s=state(id);document.title=`${i.title} · CoC Help`;
 const siblingList=issues.filter(x=>x.category===i.category);
 const articleContent=`<article class="article"><header class="article-intro"><span class="eyebrow">${e(cat(i.category).title)}</span><h1>${e(i.title)}</h1><h2 class="sr-only">Problem</h2><p>${e(i.problem)}</p><div class="caution"><span aria-hidden="true">!</span><p>${e(i.caution)}</p></div>${i.note?`<p class="source-note">${e(i.note)}</p>`:''}</header>${v===4?`<ol class="action-track">${i.steps.map((f,n)=>`<li class="${n===s.at&&s.status==='active'?'active':''}"><span>${n+1}</span>${e(f.title)}</li>`).join('')}</ol>`:''}<div class="fix-stack">${history(i,s)}${s.status==='active'?current(i,s):s.status==='support'?'':result(i,s)}</div>${related(i)}${s.status==='support'?fallback(i,s):''}${governance(i)}<button class="restart" data-restart>Start this guide again</button></article>`;
 const rail=v===2?`<aside class="workspace-nav"><a class="back" href="#home">← All topics</a><h2>${e(cat(i.category).title)}</h2>${siblingList.map(x=>`<a href="#problem/${x.id}" ${x.id===id?'aria-current="page"':''}>${e(x.title)}</a>`).join('')}</aside>`:v===1?`<aside class="reading-rail"><span class="eyebrow">Your next step</span><p>${s.status==='active'?e(i.steps[s.at].title):s.status==='support'?'Review related symptoms, then ask privately if needed.':'Follow the observed result.'}</p><div class="rail-rule"></div><span class="small">No login. No wallet connection. No request sent.</span></aside>`:'';
 const wrap=v===5?`<div class="book-article"><details class="book-switch"><summary>Other problems in ${e(cat(i.category).title)}</summary>${siblingList.filter(x=>x.id!==id).map(x=>link(x)).join('')}</details>${articleContent}</div>`:`${rail}${articleContent}`;
 app.innerHTML=`<div class="container article-container"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="#home">← Help home</a><span>/</span><a href="#category/${i.category}">${e(cat(i.category).title)}</a></nav>${v===3?'<p class="focus-progress">Problem selected <span>→</span> Safe checks <span>→</span> Your result</p>':''}<div class="article-layout">${wrap}</div></div>`;
 bindArticle(i,s);if(focus){const target=app.querySelector(s.status==='active'?'#current-step':s.status==='support'?'#support':'#outcome');target?.focus({preventScroll:true});target?.scrollIntoView({block:'nearest'});}}
function advance(i,s,label){s.history[s.at]=label;if(s.at<i.steps.length-1)s.at++;else s.status='support';article(i.id,true);}
function bindArticle(i,s){app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const a=i.steps[s.at].answers[Number(b.dataset.answer)];if(a.to.startsWith('route:')){location.hash=`#problem/${a.to.slice(6)}`;return;}if(a.to==='next'){advance(i,s,a.label);return;}s.history[s.at]=a.label;s.status=a.to;s.message=a.message;article(i.id,true);});app.querySelectorAll('[data-skip]').forEach(b=>b.onclick=()=>advance(i,s,b.dataset.skip));app.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{s.at=Number(b.dataset.edit);s.history=s.history.slice(0,s.at);s.status='active';s.message='';article(i.id,true);});app.querySelector('[data-restart]').onclick=()=>{states.delete(i.id);article(i.id,true);};app.querySelector('[data-unresolved]')?.addEventListener('click',()=>{s.status='active';s.message='';if(s.at<i.steps.length-1)s.at++;else s.status='support';article(i.id,true);});app.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=()=>{app.querySelector('.feedback-status').textContent='Thank you. Kept only in this page session.';b.setAttribute('aria-pressed','true');});}
function bindSearch(){const input=app.querySelector('#help-search');if(!input)return;const results=app.querySelector('#search-results'),status=app.querySelector('#search-status');let active=-1;function show(){active=-1;input.removeAttribute('aria-activedescendant');const found=search(input.value);results.hidden=false;input.setAttribute('aria-expanded','true');results.innerHTML=found.length?found.map((i,n)=>`<div id="search-option-${n}" role="option" aria-selected="false" data-result="${i.id}"><strong>${e(i.title)}</strong><small>${e(cat(i.category).title)}</small></div>`).join(''):'<div class="no-results">No exact match. Try fewer words or <a href="#browse">browse topics</a>.</div>';status.textContent=found.length?`${found.length} matching problems`:'No exact match. Browse topics.';results.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>location.hash=`#problem/${b.dataset.result}`);}
 input.oninput=show;input.onfocus=show;input.onkeydown=ev=>{const opts=[...results.querySelectorAll('[role=option]')];if(ev.key==='Escape'){ev.preventDefault();active=-1;results.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');return;}if(ev.key==='Enter'&&!results.hidden&&active>=0){ev.preventDefault();opts[active].click();return;}if(['ArrowDown','ArrowUp'].includes(ev.key)&&opts.length){ev.preventDefault();results.hidden=false;input.setAttribute('aria-expanded','true');active=Math.max(0,Math.min(opts.length-1,active+(ev.key==='ArrowDown'?1:-1)));opts.forEach((o,n)=>o.setAttribute('aria-selected',String(n===active)));input.setAttribute('aria-activedescendant',opts[active].id);opts[active].scrollIntoView({block:'nearest'});}};
 app.querySelector('[data-clear]').onclick=()=>{input.value='';show();input.focus();};app.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{input.value=b.dataset.query;show();input.focus();});}
function routePage(){const [route,id]=(location.hash.slice(1)||'home').split('/');if(route==='problem')article(id);else if(route==='category')browse(id);else if(route==='browse'||route==='problems')browse();else home();window.scrollTo(0,0);}
document.addEventListener('click',ev=>{if(!ev.target.closest('.search')){const r=app.querySelector('#search-results'),i=app.querySelector('#help-search');if(r)r.hidden=true;i?.setAttribute('aria-expanded','false');i?.removeAttribute('aria-activedescendant');}});
document.querySelector('.skip-link').addEventListener('click',ev=>{ev.preventDefault();app.focus();app.scrollIntoView({block:'start'});});
window.addEventListener('hashchange',routePage);routePage();
